baseurl:  #TODO 
languageCode: en-us
#theme: hugo-theme-stack hugo-theme-stack-3.17.0
theme: hugo-theme-stack-3.17.0
paginate: 6
title: Pediaku ID - Bloging & Tech Info  #TODO åšå®¢æ ‡é¢˜


languages:
  id:
    languageName: Indonesia
    weight: 1

# Change it to your Disqus shortname before using
disqusShortname: pediaku

# GA Tracking ID
googleAnalytics: G-2TLDCKC669 #TODO Googleåˆ†æ
#googleAnalytics:
# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk
DefaultContentLanguage: id

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true

permalinks:
    post: /:slug/ #TODO é“¾æ¥å½¢å¼
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: /img/favicon.ico

    footer:
        since: 2024 #TODO è¿™é‡Œæ˜¯å»ºç«™æ—¶é—´
        customText:

    dateFormat:
        #published: Jan 02, 2006
        #lastUpdated: Jan 02, 2006 15:04 MST
        published: Jan 02, 2006 
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        #emoji: â­
        subtitle: Pediaku adalah blog personal yang membahas hal-hal menarik seputar blogger, tutorial jekyll, teknologi dan tips bermain game. #TODO å‰¯æ ‡é¢˜
        avatar:
            enabled: true
            local: true
            src: /img/logo.png
            #local: false #TODO è®¾ç½®ä¸ºtrueä½¿ç”¨ç½‘ç»œå›¾ç‰‡
            #src: 

    article:
        math: true
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0 #TODO ç‰ˆæƒæ ‡è¯­

    comments:
        enabled: true
        provider: disqus

       # disqusjs:
          #  shortname:
          #  apiUrl:
          #  apiKey:
          #  admin:
          #  adminLabel:

       # utterances:
         #   repo: 
         #   issueTerm: 
         #   label: 

       # remark42:
       #     host:
        #    site:
        #    locale:

       # vssue:
         #   platform:
        #    owner:
        #    repo:
         #   clientId:
         #   clientSecret:
         #   autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client.html
      #  waline:
       #     serverURL: #TODO Waline è‡ªè¡Œé…ç½®
        #    lang:
        #    visitor: true
       #     pageview: true
       #     dark: auto
        #    emoji: #TODO èŠå¤©ä½¿ç”¨çš„emoji
                # - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
                # - https://cdn.jsdelivr.net/gh/walinejs/emojis/bilibili@1.0.6
        #    requiredMeta:
           #     - name
           #     - email
          #      - url
         #   locale:
        #        admin: åšä¸» 
         #       placeholder: æœ‰ä»€ä¹ˆæ–°ç‚¹å­ï¼ŸğŸ‰ï¼ˆä¸Šæ–¹ç•™ä¸‹é‚®ç®±å¯ä»¥æ”¶åˆ°é€šçŸ¥å“¦ï¼‰

        twikoo:
            envId:
            region:
            path:
            lang:

        # See https://cactus.chat/docs/reference/web-client/#configuration for description of the various options
        cactus:
            defaultHomeserverUrl: "https://matrix.cactus.chat:8448"
            serverName: "cactus.chat"
            siteName: "" # You must insert a unique identifier here matching the one you registered (See https://cactus.chat/docs/getting-started/quick-start/#register-your-site)

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0

        gitalk:
            owner: 
            admin:  
            repo: 
            clientID: 
            clientSecret: 
        
        cusdis:
            host: 
            id: 

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                limit: 5
            #- type: timeline
            #  params:
            #      limit: 10
            - type: categories
              params:
                  limit: 10
           # - type: tag-cloud
            #  params:
             #     limit: 100
            - type: ads
            #  params:
              #    limit: 100
            
            #- type: typeform-widget
        page:
            - type: search
            - type: toc
            - type: categories
              params:
                  limit: 10
            #- type: typeform-widget

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu

### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          params:
              ### For demonstration purpose, the home link will be open in a new tab
              newTab: false
              icon: newspaper-regular

        - identifier: Ujian Online
          name: Try Out Gratis
          url: https://akazed.com/ujian/
          weight: -50
          params:
               ### For demonstration purpose, the home link will be open in a new tab
              newTab: false
              icon: train-subway-solid

        - identifier: Blogger
          name: Blogger
          url: /categories/blogger/
          weight: -50
          params:
               ### For demonstration purpose, the home link will be open in a new tab
              newTab: false
              icon: train-subway-solid

        ##- identifier: aa
         ## name: aa
         ## url: https://foreverblog.cn/go.html
        ##  weight: -40
        ##  params:
              ### For demonstration purpose, the home link will be open in a new tab
           ##   newTab: true
           ##   icon: record-vinyl-solid

    #social:
        #- identifier: github
        #  name: GitHub
        #  url: https://github.com/irithys #TODO è¿™é‡Œæ˜¯ä½ çš„Githubé“¾æ¥
        #  params:
        #    icon: brand-github
        
        #- identifier: travellings
        #  name: å¼€å¾€
        #  url: https://travellings.link
        #  params:
        #    icon: train-subway-solid
        #    newTab: true
            

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4

ignoreErrors: "error-remote-getjson"